// ── SONGS DATA ──────────────────────────
// All songs from Songs.zip
const SONGS = [
  { id: 0,  file: "Bazzi - Why (Lyrics).mp3",                                                                    artist: "Bazzi",                    title: "Why" },
  { id: 1,  file: "Ben&Ben - Lifetime (Reimagined) (Lyrics).mp3",                                                artist: "Ben&Ben",                  title: "Lifetime (Reimagined)" },
  { id: 2,  file: "Chase Atlantic - Consume feat. Goon Des Garcons (Lyrics).mp3",                                artist: "Chase Atlantic",           title: "Consume ft. Goon Des Garcons" },
  { id: 3,  file: "Chase Atlantic - HEAVEN AND BACK (Lyrics).mp3",                                               artist: "Chase Atlantic",           title: "Heaven and Back" },
  { id: 4,  file: "Chase Atlantic - Swim (Lyrics).mp3",                                                          artist: "Chase Atlantic",           title: "Swim" },
  { id: 5,  file: "Chris Brown - New Flame (Lyrics) ft. Usher, Rick Ross.mp3",                                   artist: "Chris Brown",              title: "New Flame ft. Usher, Rick Ross" },
  { id: 6,  file: "Confident - Justin Bieber ft Chance The Rapper Lyrics.mp3",                                   artist: "Justin Bieber",            title: "Confident ft. Chance The Rapper" },
  { id: 7,  file: "Demi - homebdy (Lyrics) ft. Madman Stan.mp3",                                                 artist: "Demi",                     title: "Homebdy ft. Madman Stan" },
  { id: 8,  file: "DEMI - Pakundangan ft. Hev Abi (Lyrics).mp3",                                                 artist: "DEMI",                     title: "Pakundangan ft. Hev Abi" },
  { id: 9,  file: "Doja Cat - Agora Hills (Lyrics).mp3",                                                         artist: "Doja Cat",                 title: "Agora Hills" },
  { id: 10, file: "Doja Cat - Ain't Shit (Lyrics).mp3",                                                          artist: "Doja Cat",                 title: "Ain't Shit" },
  { id: 11, file: "Doja Cat - Been Like This (Lyrics).mp3",                                                      artist: "Doja Cat",                 title: "Been Like This" },
  { id: 12, file: "Doja Cat - Need To Know (Lyrics).mp3",                                                        artist: "Doja Cat",                 title: "Need To Know" },
  { id: 13, file: "Doja Cat - So High (Lyrics).mp3",                                                             artist: "Doja Cat",                 title: "So High" },
  { id: 14, file: "Doja Cat - Streets (Silhouette Remix) [Lyrics].mp3",                                          artist: "Doja Cat",                 title: "Streets (Silhouette Remix)" },
  { id: 15, file: "Doja Cat - Woman (Lyrics).mp3",                                                               artist: "Doja Cat",                 title: "Woman" },
  { id: 16, file: "Doja Cat, The Weeknd - You Right (Lyrics).mp3",                                               artist: "Doja Cat & The Weeknd",    title: "You Right" },
  { id: 17, file: "Future - Same Damn Time (Official Lyric Video).mp3",                                          artist: "Future",                   title: "Same Damn Time" },
  { id: 18, file: "Jacquees - B.E.D (lyrics).mp3",                                                              artist: "Jacquees",                 title: "B.E.D" },
  { id: 19, file: "Jeff Buckley - Everybody Here Wants You (Lyrics).mp3",                                        artist: "Jeff Buckley",             title: "Everybody Here Wants You" },
  { id: 20, file: "Jeremih - Birthday Sex.mp3",                                                                  artist: "Jeremih",                  title: "Birthday Sex" },
  { id: 21, file: "Kevin Gates ft Doe B - Amnesia (Official Music Video).mp3",                                   artist: "Kevin Gates ft. Doe B",    title: "Amnesia" },
  { id: 22, file: "Lah Pat  - Rodeo (feat. Flo Milli] [Remix] [Official Lyric Video].mp3",                      artist: "Lah Pat",                  title: "Rodeo (feat. Flo Milli) Remix" },
  { id: 23, file: "Liam Payne - Strip That Down (Lyric Video) ft. Quavo.mp3",                                    artist: "Liam Payne",               title: "Strip That Down ft. Quavo" },
  { id: 24, file: "Lloyd - All I Need (Lyrics).mp3",                                                             artist: "Lloyd",                    title: "All I Need" },
  { id: 25, file: "LPB Poody - Batman (Lyrics) ft. Lil Wayne & Moneybagg Yo.mp3",                               artist: "LPB Poody",                title: "Batman ft. Lil Wayne & Moneybagg Yo" },
  { id: 26, file: "Ludacris - What's Your Fantasy ft. Shawnna (Lyrics).mp3",                                     artist: "Ludacris",                 title: "What's Your Fantasy ft. Shawnna" },
  { id: 27, file: "Mia Martina ft. Waka Flocka - Beast (lyrics).mp3",                                           artist: "Mia Martina ft. Waka Flocka", title: "Beast" },
  { id: 28, file: "PARTYNEXTDOOR - MAKE IT TO THE MORNING (Lyrics).mp3",                                         artist: "PARTYNEXTDOOR",            title: "Make It to the Morning" },
  { id: 29, file: "Petey Pablo - Freek-A-Leek (Lyrics).mp3",                                                     artist: "Petey Pablo",              title: "Freek-A-Leek" },
  { id: 30, file: "Sean Kingston - Beat It (Lyrics) ft. Chris Brown & Wiz Khalifa  He aint fly no, he dont even drive.mp3", artist: "Sean Kingston",  title: "Beat It ft. Chris Brown & Wiz Khalifa" },
  { id: 31, file: "Sexyy Red, Bruno Mars - Fat Juicy & Wet (Lyrics).mp3",                                        artist: "Sexyy Red & Bruno Mars",   title: "Fat Juicy & Wet" },
  { id: 32, file: "Skate Avenue PH - Heaven Knows (Rock Cover).mp3",                                             artist: "Skate Avenue PH",         title: "Heaven Knows (Rock Cover)" },
  { id: 33, file: "Spiffy The Goat - Make It Move! [Lyrics].mp3",                                                artist: "Spiffy The Goat",         title: "Make It Move!" },
  { id: 34, file: "Ty Dolla $ign - Or Nah (feat. The Weeknd, Wiz)  Lyrics.mp3",                                  artist: "Ty Dolla $ign",            title: "Or Nah ft. The Weeknd & Wiz" },
  { id: 35, file: "Waka Flocka Flame - No Hands (feat. Roscoe Dash and Wale)  Lyrics.mp3",                       artist: "Waka Flocka Flame",        title: "No Hands ft. Roscoe Dash & Wale" },
  { id: 36, file: "Zeddy Will - YUP AND I DO (Lyrics).mp3",                                                      artist: "Zeddy Will",              title: "YUP AND I DO" }
];